import SwiftUI

/// The Swoop brand glyph: a bird in a vertical dive whose swept-back wings form a download arrow,
/// above a water line. Monochrome, drawn in a square frame (aspect-fit and centred in `rect`), so it
/// can be filled with any style: `SwoopGlyph().fill(.white).frame(width: 18, height: 18)`.
/// Generated by scripts/render-icon.swift; coordinates are on a 1000-unit grid.
struct SwoopGlyph: Shape {
    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height)
        let ox = rect.midX - side / 2, oy = rect.midY - side / 2
        func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: ox + x / 1000 * side, y: oy + y / 1000 * side) }
        var path = Path()
        path.move(to: p(500, 787.92))
        path.addCurve(to: p(977.12, 174.49), control1: p(603.6, 673.42), control2: p(779.45, 419.86))
        path.addCurve(to: p(562.71, 406.23), control1: p(833.98, 264.46), control2: p(670.4, 362.61))
        path.addCurve(to: p(536.81, 140.41), control1: p(553.16, 310.81), control2: p(542.26, 215.38))
        path.addCurve(to: p(584.52, 0), control1: p(546.35, 85.88), control2: p(565.43, 35.44))
        path.addQuadCurve(to: p(500, 59.98), control: p(535.44, 16.36))
        path.addQuadCurve(to: p(415.48, 0), control: p(464.56, 16.36))
        path.addCurve(to: p(463.19, 140.41), control1: p(434.57, 35.44), control2: p(453.65, 85.88))
        path.addCurve(to: p(437.29, 406.23), control1: p(457.74, 215.38), control2: p(446.84, 310.81))
        path.addCurve(to: p(22.88, 174.49), control1: p(329.6, 362.61), control2: p(166.02, 264.46))
        path.addCurve(to: p(500, 787.92), control1: p(220.55, 419.86), control2: p(396.4, 673.42))
        path.closeSubpath()
        path.move(to: p(202.88, 964.05))
        path.addCurve(to: p(485.51, 951.66), control1: p(298.62, 897.03), control2: p(388.39, 894.68))
        path.addCurve(to: p(829.95, 936.79), control1: p(601.69, 1019.82), control2: p(715.61, 1016.83))
        path.addCurve(to: p(836.99, 896.92), control1: p(842.9, 927.72), control2: p(846.05, 909.87))
        path.addCurve(to: p(797.12, 889.88), control1: p(827.92, 883.97), control2: p(810.07, 880.82))
        path.addCurve(to: p(514.49, 902.28), control1: p(701.38, 956.9), control2: p(611.61, 959.26))
        path.addCurve(to: p(170.05, 917.15), control1: p(398.31, 834.12), control2: p(284.39, 837.11))
        path.addCurve(to: p(163.01, 957.02), control1: p(157.1, 926.21), control2: p(153.95, 944.06))
        path.addCurve(to: p(202.88, 964.05), control1: p(172.08, 969.97), control2: p(189.93, 973.12))
        path.closeSubpath()
        return path
    }
}
